--- #YAML:1.0
name:                Config-LotusNotes
version:             0.31
abstract:            Access Lotus Notes/Domino configuration
license:             ~
author:              
    - Harald Albers <albers@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42_01
distribution_type:   module
requires:     
    Config::IniHash:               0
    File::HomeDir:                 0
    Win32::TieRegistry:            0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
