# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Config-LotusNotes
version:      0.30
version_from: lib/Config/LotusNotes.pm
installdirs:  site
requires:
    Config::IniHash:               0
    Win32::TieRegistry:            0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
