--- #YAML:1.0
name:               Config-LotusNotes
version:            0.33
abstract:           Access Lotus Notes/Domino configuration
author:
    - Harald Albers <albers@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
    Test::Pod:            1.00
    Test::Pod::Coverage:  1.04
requires:
    Config::IniHash:     0
    File::HomeDir:       0
    Win32::TieRegistry:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
